name: Generate README file
description: Generates a README file for a specific branch
inputs:
  environment-name:
    description: Name of the environment to which the README file belongs
    required: true
  target-branch:
    description: Name of the branch to add the README to
    required: true

runs:
  using: composite
  steps:
    - name: Generate README
      run: |
        git checkout -b readme-update-${{ inputs.environment-name }}
        make readme ENVIRONMENT_NAME='${{ inputs.environment-name }}'
      shell: bash
    - name: Commit README
      run: |
        git config --global user.email "github-actions@example.com"
        git config --global user.name "GitHub README Action"
        git add -f README.md
        git commit -m "Updating ${{ inputs.environment-name }} README file"
        git push --set-upstream origin readme-update-${{ inputs.environment-name }}
      shell: bash
    - name: Look for existing open PR
      run: |
        pullreqnumber="$(gh pr status --json number,baseRefName,state -q '.currentBranch | select((.baseRefName == "${{ inputs.target-branch }}") and (.state == "OPEN")) | .number')"
        echo 'PULL_REQ_NUMBER='$pullreqnumber >> $GITHUB_ENV
      shell: bash
    - name: Create PR
      id: create-pr
      if: env.PULL_REQ_NUMBER == ''
      run: |
        gh pr create --base ${{ inputs.target-branch }} --head readme-update-${{ inputs.environment-name }} --title 'README Update: ${{ inputs.environment-name }} Update.' --body "Updating ${{ inputs.environment-name }} README file"
      shell: bash