name: Generate README file
on:
  workflow_dispatch:
    inputs:
      lowest_branch:
        type: choice
        description: 'Branch corresponding to the lowest application environment'
        required: true
        default: 'dev'
        options:
          - dev
          - test
          - staging
          - main

permissions:
      id-token: write
      contents: write
      pull-requests: write
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
jobs:
  GenerateReadMe:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Generate README
        run: |
          git checkout -b readme-update-${{ github.event.inputs.lowest_branch }}
          make readme
      - name: Commit README
        run: |
          git config --global user.email "${{ github.actor }}@hss.edu"
          git config --global user.name "${{ github.actor }}"
          git add README.md
          git commit -m "Updating README file on ${{ github.event.inputs.lowest_branch }} branch"
          git push --set-upstream origin readme-update-${{ github.event.inputs.lowest_branch }}
      - name: Create PR
        id: create-pr
        run: |
          gh pr create --base ${{ github.event.inputs.lowest_branch }} --head readme-update-${{ github.event.inputs.lowest_branch }} --title 'README Update: ${{ github.event.inputs.lowest_branch }} Update.' --body "Updating README file on ${{ github.event.inputs.lowest_branch }} branch"
