name: Generate README file
on:
  push:
    paths:
      - 'config/project_info.json'
    branches:
      - dev
permissions:
      id-token: write
      contents: write
      pull-requests: write
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
jobs:
  GenerateReadMe:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Generate README
        run: |
          git checkout -b readme-update-dev
          make readme
      - name: Commit README
        run: |
          git config --global user.email "github-actions@example.com"
          git config --global user.name "GitHub README Action"
          git add README.md
          git commit -m "Updating README file on dev branch"
          git push --set-upstream origin readme-update-dev
      - name: Create PR
        id: create-pr
        if: env.PULL_REQ_NUMBER == ''
        run: |
          gh pr create --base dev --head readme-update-dev --title 'README Update: Dev Update.' --body "Updating README file on dev branch"