name: Generate Staging README file
on:
  push:
    paths:
      - 'config/account_info.staging.json'
    branches:
      - staging
permissions:
      id-token: write
      contents: write
      pull-requests: write
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
jobs:
  GenerateReadMe:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Generate README Update
        uses: ./.github/actions/generate-readme
        with:
          environment-name: 'staging'
          target-branch: 'staging'